
"""
Django settings for mybbs project.

Generated by 'django-admin startproject' using Django 1.8.3.

"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#jxvlly=_#$p%8+akfgrsmn021-1=s#29yivk16mp(46)_cb=t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'bb',
    'bbs_account',
    'utils',
    'DjangoUeditor',
    'django.contrib.sites',
    'debug_toolbar',
)

SITE_ID = 1

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
)

ROOT_URLCONF = 'mybbs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mybbs.wsgi.application'


AUTH_USER_MODEL = 'bbs_account.Account'

# A simple backend which allows you to login with either an email address or a username.
# It should be combined with another backend for checking permissions:
AUTHENTICATION_BACKENDS = ('bbs_account.backends.EmailOrUsernameModelBackend',
                           'django.contrib.auth.backends.ModelBackend'
                           )

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static', 'staticfiles'),)

STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'staticroot')

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')

MEDIA_URL = '/media/'
ADMIN_MEDIA_PREFIX='/admin_media/'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mail@ratankumar.org'
EMAIL_HOST_PASSWORD = 'ccsqoswplgxenrtk'
EMAIL_PORT = 587
SITE_HOST = '127.0.0.1:8000'

ADMIN = 'cundi'

LOGIN_REDIRECT_URL = '/'

TEMPLATE_DEBUG = True

ATTACHMENT_UPLOAD_TO = os.path.join(BASE_DIR, 'static', 'staticfiles/attachments')
FORUM_LOGO_UPLOAD_TO = os.path.join(BASE_DIR, 'static', 'staticfiles/forum_logo')
FORUM_LOGO_WIDTH = 16
FORUM_LOGO_HEIGHT = 16
FORUM_DISABLE_NOTIFICATIONS = False
FORUM_USE_DJANGO_MAILER = False
FORUM_ENABLE_ANONYMOUS_POST = False
FORUM_ANONYMOUS_USERNAME = 'Anonymous'
FORUM_DISABLE_SUBSCRIPTIONS = False
FORUM_DEFAULT_AUTOSUBSCRIBE = True
FORUM_PROFILE_RELATED_NAME = 'bbs_account_account'
FORUM_PREMODERATION = False
FORUM_ATTACHMENT_ENABLE = False
FORUM_PERMISSION_HANDLER  = 'bb.permission.DefaultPermissionHandler'
FORUMS_EDIT_TIMEOUT = 60
FORUM_TOPIC_PAGE_SIZE = 10



NOTIFY_ON_PASSWORD_CHANGE = True
SIGNATURE_MAX_LENGTH = 1024
SIGNATURE_MAX_LINES = 3
DEFAULT_TIME_ZONE = 8
